title: In Her Own Write
email: inherownwriteblog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Too meta for Insta.
author: In Her Own Write
baseurl:            ""
url:                "inherownwrite.com"

# Social Profiles
twitter_username: yycheung
github_username:  veronicacheung
linkedin_username: veronica-cheung

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-175285034-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

